### ISSUE TITLE
Bug: vault.auth_methods_synced enable auth methods at the incorrect path

### ISSUE THREAD

**Issue by allez-allez-allez** [plus3it/terraform-aws-vault#10]
**Describe the bug**
`vault.auth_methods_synced` state module does not provision `path` correctly. 

**To Reproduce**
Specify these config in the pillar:
```yaml
- type: aws
   path: auth/aws
   description: Vault AWS auth method
   config:
     default_lease_ttl: 0
     max_lease_ttl: 0
```
and then run 
`[root@node1 ~]# salt-call --local state.sls vault.sync -l debug`

`aws` auth method is enabled at that path `authaws/`

**Expected behavior**
New `aws` auth method should be enabled at the path `auth/aws/`
